# Generated by Django 3.0.8 on 2020-08-15 10:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_profile_about_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 15, 10, 47, 53, 784011, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='profile',
            name='child_amount',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='genre',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='locatity',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('d', 'Divorsed'), ('C', 'Complecated')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code_3',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code_4',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
