# Generated by Django 3.0.8 on 2020-08-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200815_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
