# Generated by Django 3.0.8 on 2020-08-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200815_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
