# Generated by Django 3.0.8 on 2020-08-15 11:09

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True)),
                ('genre', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('postal_code_4', models.PositiveIntegerField(null=True)),
                ('postal_code_3', models.PositiveIntegerField(null=True)),
                ('locatity', models.CharField(max_length=30, null=True)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('d', 'Divorsed'), ('C', 'Complecated')], max_length=1, null=True)),
                ('child_amount', models.PositiveSmallIntegerField(null=True)),
                ('about_user', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
